version: '3'

services:
  postgres:
    image: postgres:10.5
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'PGPASSWORD=1234567890 PGUSER=postgres pg_isready -h postgres -d blogspot',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=blogspot
    ports:
      - '25432-25452:5432'
    volumes:
      - data-volume:/data/db
  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:4000
    restart: always
    env_file:
      - .env.docker
    environment:
      WAIT_HOSTS: postgres:5432
    networks:
      - blogger_default
      - default
volumes:
  data-volume:
networks:
  blogger_default:
    external: true
