version: '3'

services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=blogspot
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/data/db
  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:4000
    restart: always
    env_file:
      - .env.docker
    environment:
      WAIT_HOSTS: postgres:5432
    networks:
      - blogger_default
      - default
volumes:
  data-volume:
networks:
  blogger_default:
    external: true
